### ISSUE TITLE
Using paras/tmp is not compatible with shared conda environments

### ISSUE THREAD

**Issue by snail123815** [BTheDragonMaster/parasect#1]
Hi Barbara, maybe you already know this but in case you don't.

I set parasect up in a shared conda environment. For this environment, I can use for fine. However, it needs to be shared as J don't know how to set it up by himself. Also when multiple person is using the same program, if they use the same environment, it will save quite some spaces on the server.

All the dirs created by environment manager are 755, files are 644, meaning, other users can use this environment, but cannot modify it. When a specific file is written to the environment, it will report premission error.

In the case of parasect, 

```
Permission denied: '/vol/local/conda_envs/parasect/lib/python3.9/site-packages/paras/tmp/proteins_from_genbank.fasta'
```

I think using python's `tempfile.NamedTemporaryFile` should solve the issue. It deals with such problems by creating a system tmp file.

I did not read the code, sorry if you have already solved it.

**Comment by davidmeijer** [comment]
Hi @snail123815, thank you for bringing this to our attention. While we refactor the code to address your issue, you can also use the UI here: `https://paras.bioinformatics.nl/`. Most functionalities from the command line interface are implemented in the UI.

**Comment by davidmeijer** [comment]
Hi @snail123815, we have created a minimal working version of PARAS(ECT) for the [webapp branch](https://github.com/BTheDragonMaster/parasect/tree/webapp). Perhaps you can check out the [API](https://github.com/BTheDragonMaster/parasect/blob/webapp/src/parasect/api.py) for the backend, which allows you to set the temporary folder manually. 

Let me know if this provides a solution for you. I am going to close this issue for now.
