### ISSUE TITLE
Add active site signature to results page

### ISSUE THREAD

**Issue by BTheDragonMaster** [BTheDragonMaster/parasect#2]
Suggested feature: when selected, also visualise the (extended) active site signature and/or adenylation domain sequence on the domain results page.

**Comment by davidmeijer** [comment]
I have refactored the front end (see screenshot of results page). One additional feature is that you can now see the signature and copy it to the clipboard. You can also copy the adenylation domain's extended signature and amino acid sequence. However, visualizing the extended signatures and the amino acid sequences will look clunky, as they are pretty long.

![Screenshot 2024-10-15 at 14 33 29](https://github.com/user-attachments/assets/9aa83578-4b1a-4daf-9905-0f87f3326495)
