### ISSUE TITLE
Webapp: PARASECT doesn't parse SMILES file correctly

### ISSUE THREAD

**Issue by BTheDragonMaster** [BTheDragonMaster/parasect#3]
When uploading a .txt file with one SMILES per line, I get the following error:

```
Failed to parse SMILES strings: expected str, bytes or os.PathLike object, not list
```

**Comment by davidmeijer** [comment]
Uploading own SMILES strings should now work properly. Could you check for your input if everything is in order?

**Comment by davidmeijer** [comment]
This is now fixed.
